from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
import os, json

# Write credentials from GitHub secret
with open("gdrive_key.json", "w") as f:
    f.write(os.environ["GDRIVE_KEY"])

# Authenticate
gauth = GoogleAuth()
gauth.LoadServiceConfigFile("gdrive_key.json")
drive = GoogleDrive(gauth)

# Replace with your folder ID (from Google Drive URL)
FOLDER_ID = "1QyoY1rs9Mv1yHa9-XDXGPZ4VK8ETduY3"

# File generated by your scraper
file_name = "yellowpages_hammer_unions.csv"

# Upload file to Drive
gfile = drive.CreateFile({
    "title": file_name,
    "parents": [{"id": FOLDER_ID}]
})
gfile.SetContentFile(file_name)
gfile.Upload()

print(f"✅ Uploaded {file_name} to Google Drive folder {FOLDER_ID}")
