name: run-script

on:
  schedule:
    - cron: '58 9 * * 0'  # Runs every Sunday at 4:30 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install dependencies
        run: pip install -r requirements.txt pydrive2

      - name: Run script
        run: python yellowpages_hammer_unions.py

      - name: Upload to Google Drive
        env:
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}
        run: python upload_to_drive.py
