name: run-script

on:
  schedule:
    - cron: '58 9 * * 0'  # Runs every Sunday at 9:58 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python yellowpages_hammer_unions.py

      # 🔹 Install rclone (this was missing)
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Upload to OneDrive
        run: rclone copy yellowpages_hammer_unions.csv onedrive:/PowerBI/ --progress

      - name: List files in OneDrive
        run: rclone ls onedrive:/PowerBI
